export const Roles = [
    "ADMIN - Administrator of the whole application",
    "ASSAY COMPONENET CREATOR - Role to create assays components(primers,probes)",
    "ASSAY CREATOR - Role to create new assays",
    "ASSAY VIEWER - Role to consult DNA sequences of assays",
    "CONSENSUS CONTRIBUTER - Responsible for maintaining of consensus maps",
    "CONSENSUS PUBLISHER - Responsible for publication of Consensus maps",
    "DEFAULT LAB FUNCTIONS - DEFAULT LAB FUNCTIONS",
    "MGB_TO_BHQ_ASSAY_CONVERTOR - MGB TO BHQ ASSAY CONVERTOR",
    "POPULATION CONTRIBUTER - Responsible for maintaining pf Population maps",
    "POPULATION PUBLISHER - Responsible for publication of Population maps",
    "REF DATA ADMIN - Role to administrate business reference data",
    "REFERENCE CONTRIBUTER - Responsible for maintaining of Reference maps",
    "REFERENCE PUBLISHER - Responsible for publication of Reference maps",
    "SSP USER - Role For SSP USER To Upload Samples To Magenta"
];
export const CropGroups = [
    "B - Barley",
    "N - Beans",
    "O - Brassica oleracea",
    "A - Brassica rapa",
    "C - Cucumber",
    "D - Daicon",
    "G - Flowers",
    "2 - Glycine spp",
    "1 - Kingdom Animalia",
    "L - Lettuce",
    "M - Maize",
    "E - Melon",
    "R - Oilseed Rape",
    "U - Onion",
    "3 - Orobanche",
    "P - Pepper",
    "X - Rice",
    "J - Rye-grass",
    "Y - Soybeans",
    "I - Spinach",
    "Q - Squash",
    "S - Sugarbeet",
    "K - Sugarcane",
    "F - Sunflower",
    "Z - Sweetcorn",
    "T - Tomato",
    "V - Vegetables",
    "H - Watermelon",
    "W - Wheat"
];
export const labsLocation = [
    "Bejing Changping",
    "Contract - IIlumina",
    "Contract KBiosciences",
    "Enkhuizen",
    "Ghant",
    "Gilroy",
    "Landskrona",
    "Novartis",
    "Plant Analysis Group SBI",
    "Santiago",
    "Sarrians",
    "Singapore",
    "Slater",
    "Stanton",
    "Toulouse",
    "Uberlandia"
];